# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'swiftHW2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swiftHW2
pod 'RxSwift', '~> 5'
pod 'Alamofire', '~> 4.4'
end
